name = "audience-acuity-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "208f128290b10d58d5de18909148acc0"

[vars]
AA_ORIGIN = "https://api.audienceacuity.com"
MYSQL_API_URL = "https://your-mysql-api.up.railway.app"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "audience-acuity-db"
database_id = "cc37296b-7367-401d-a8bc-5a413caa720d"

# To set secrets, run:
# wrangler secret put AA_KEY_ID
# wrangler secret put AA_SECRET
